import { Bot, Sparkles, BadgeCheck, TrendingUp } from "lucide-react";

export default function AIRecommendation({ product }) {
  const aiMatch = product.aiMatch || Math.floor(Math.random() * 6) + 95;

  return (
    <section className="mt-16 rounded-3xl bg-gradient-to-r from-emerald-600 to-green-700 text-white shadow-xl overflow-hidden">

      <div className="p-10">

        <div className="flex items-center gap-3">

          <Bot size={34} />

          <div>
            <h2 className="text-3xl font-bold">
              AI Recommendation
            </h2>

            <p className="text-emerald-100 mt-1">
              Personalized recommendation generated by TexMind AI
            </p>

          </div>

        </div>

        <div className="grid lg:grid-cols-2 gap-8 mt-10">

          {/* Left Side */}

          <div>

            <h3 className="text-4xl font-bold">
              {product.name}
            </h3>

            <p className="text-emerald-100 mt-3">
              {product.description}
            </p>

            <div className="mt-8 space-y-4">

              <div className="flex items-center gap-3">
                <Sparkles className="text-yellow-300" />
                <span>
                  Best suited for {product.category}
                </span>
              </div>

              <div className="flex items-center gap-3">
                <BadgeCheck />
                <span>
                  Verified Supplier
                </span>
              </div>

              <div className="flex items-center gap-3">
                <TrendingUp />
                <span>
                  High Demand Product
                </span>
              </div>

              <div className="flex items-center gap-3">
                <Bot />
                <span>
                  AI predicts excellent customer satisfaction
                </span>
              </div>

            </div>

          </div>

          {/* Right Side */}

          <div className="bg-white/15 rounded-3xl p-8 backdrop-blur">

            <h3 className="text-xl font-semibold">
              AI Match Score
            </h3>

            <h1 className="text-7xl font-extrabold mt-3">
              {aiMatch}%
            </h1>

            <div className="w-full h-4 bg-white/20 rounded-full mt-8 overflow-hidden">

              <div
                className="h-full bg-white rounded-full transition-all duration-700"
                style={{
                  width: `${aiMatch}%`,
                }}
              />

            </div>

            <div className="mt-8 space-y-2 text-lg">

              <p>
                ✔ Price: ₹{product.price}
              </p>

              <p>
                ✔ Stock Available: {product.stock}
              </p>

              <p>
                ✔ Category: {product.category}
              </p>

              <p>
                ✔ Ready for Immediate Purchase
              </p>

            </div>

          </div>

        </div>

      </div>

    </section>
  );
}