export const chatAI = async (req, res) => {

    const { prompt } = req.body;

    const answer = `AI Recommendation

For "${prompt}"

Recommended Fabric:
• Premium Cotton
• Linen Blend
• Organic Cotton

Supplier Confidence : 96%

Expected Price :
₹180 - ₹260 / meter

This recommendation is generated by TexMind AI.`;

    res.json({
        success:true,
        answer
    });

};